"""create historico chamados table

Revision ID: 4735a09f28a8
Revises: d03f13bb3496
Create Date: 2026-09-15 21:12:22.516278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4735a09f28a8'
down_revision: Union[str, Sequence[str], None] = 'd03f13bb3496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historico_chamados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamado_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamados.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_chamados_id'), 'historico_chamados', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historico_chamados_id'), table_name='historico_chamados')
    op.drop_table('historico_chamados')
    # ### end Alembic commands ###
